export const STRINGS = {
  app: {
    name: 'REURBCAD',
    subtitle: 'Cadastro de Campo',
  },
  auth: {
    loginTitle: 'Entrar no CARF',
    loginSubtitle: 'Acesse com seu CPF e senha',
    loginButton: 'Entrar com CARF',
    logoutConfirm: 'Deseja realmente sair?',
    sessionExpired: 'Sua sessão expirou. Faça login novamente.',
    offlineExpired: 'Você está offline há mais de 30 dias. Conecte-se para renovar.',
    loading: 'Verificando credenciais...',
  },
  roleSelection: {
    title: 'Como deseja atuar?',
    coordinator: 'Coordenador de Campo',
    coordinatorDesc: 'Gerencia equipe, visualiza todas as unidades e sincroniza dados',
    cadastrator: 'Cadastrador de Campo',
    cadastratorDesc: 'Realiza cadastros em campo com foco no mapa',
  },
  map: {
    title: 'Mapa de Campo',
    createPin: 'Tocar no mapa para criar ponto',
    newUnit: 'Nova Unidade',
    newHolder: 'Novo Titular',
    layers: 'Camadas',
    newPoint: 'Novo ponto',
    relocatePin: 'Deseja trocar a localização do ponto?',
    relocatePinWithDraft: 'Você já tem um cadastro em andamento. O que deseja fazer?',
    movePin: 'Mover ponto',
    newUnitPin: 'Nova unidade',
    unitInfo: 'Informações da Unidade',
    viewDetails: 'Ver Detalhes',
    usageLabel: 'Tipo de Uso',
    conditionLabel: 'Condição',
    clusterUnits: 'unidades',
    regionRequired: 'Selecione uma região',
    regionRequiredDesc: 'Escolha a região de atuação no seletor acima antes de criar unidades.',
  },
  unit: {
    title: 'Unidade',
    listTitle: 'Unidades',
    newTitle: 'Nova Unidade',
    editTitle: 'Editar Unidade',
    deleteConfirm: 'Deseja excluir esta unidade?',
    submitConfirm: 'Enviar para análise? Esta ação não pode ser desfeita.',
    createButton: 'Criar Unidade',
    continueButton: 'Continuar Cadastro',
    viewDetails: 'Ver Detalhes',
    saveButton: 'Salvar Unidade',
    locationLabel: 'Localização',
    stepsLabel: 'Passos do Cadastro',
    gpsAcquired: 'GPS capturado',
    holderSection: 'Titular',
    phase3Notice: 'Formulário completo com validação será implementado na Fase 3',
    fieldCount: 'campos',
  },
  holder: {
    title: 'Titular',
    newTitle: 'Novo Titular',
    cpfLabel: 'CPF',
    cpfPlaceholder: '000.000.000-00',
    nameLabel: 'Nome Completo',
    createButton: 'Criar Titular',
    scanDocument: 'Escanear documento (OCR)',
    typeManually: 'Digitar CPF manualmente',
    linkButton: 'Vincular Titular',
    noneLinked: 'Nenhum titular vinculado',
  },
  ocr: {
    selectTitle: 'Tipo de Documento',
    selectCNH: 'CNH - Carteira Nacional de Habilitação',
    selectRG: 'RG / CIN - Carteira de Identidade',
    instructions: 'Instruções de Captura',
    instructionItems: [
      {
        title: 'Modo paisagem',
        description: 'A câmera vai abrir na horizontal automaticamente para enquadrar o documento.',
      },
      {
        title: 'Boa iluminação',
        description: 'Posicione o documento em local bem iluminado, evitando sombras e reflexos.',
      },
      {
        title: 'Documento em mãos',
        description: 'Segure o documento firme sobre uma superfície lisa e escura.',
      },
      {
        title: 'Lente limpa',
        description: 'Verifique se a lente da câmera está limpa antes de capturar.',
      },
    ],
    ocrRetry: 'Tentar novamente',
    ocrRetakeCapture: 'Refazer captura',
    ocrErrorTitle: 'Não foi possível ler o documento',
    ocrErrorDescription: 'A foto pode estar escura, desfocada ou o documento mal posicionado. Tente novamente com melhor iluminação.',
    startCapture: 'Iniciar Captura',
    processing: 'Processando documento...',
    retake: 'Refazer',
    usePhoto: 'Usar esta foto',
    captureBack: 'Capturar Verso do Documento',
    confirmReturn: 'Confirmar e Voltar',
    confidence: {
      high: 'Alta confiança',
      medium: 'Média confiança',
      low: 'Baixa confiança',
    },
  },
  scan: {
    title: 'Escanear Documento',
    docTypeLabel: 'Tipo de Documento',
    docTypePlaceholder: 'Selecione o tipo de documento',
    docTypeCNH: 'CNH - Carteira Nacional de Habilitação',
    docTypeRG: 'RG / CIN - Carteira de Identidade',
    hint: 'Selecione o tipo de documento acima para liberar a captura',
    scanButton: 'Escanear Documento',
    manualButton: 'Preencher Manualmente',
    continueButton: 'Continuar',
    selectDocTypeButton: 'Selecione o tipo de documento',
    resultLabel: 'Documento capturado',
    recaptureButton: 'Capturar Novamente',
  },
  sync: {
    title: 'Sincronização',
    syncing: 'Sincronizando...',
    lastSync: 'Última sincronização',
    pending: 'operações pendentes',
    allSynced: 'Tudo sincronizado',
    syncNow: 'Sincronizar Agora',
    conflict: 'Conflito detectado. Escolha qual versão manter.',
    error: 'Erro na sincronização',
  },
  team: {
    title: 'Equipe',
    members: 'Membros',
    filterToday: 'Hoje',
    filterWeek: 'Semana',
    filterTotal: 'Total',
  },
  regiao: {
    title: 'Região',
    placeholder: 'Mapa da região de atuação — em breve',
    croquiTitle: 'Croqui da Região',
    editCroqui: 'Editar Croqui',
  },
  quadra: {
    title: 'Quadras',
    createButton: 'Nova Quadra',
    editBoundary: 'Editar Limite',
    code: 'Código',
    name: 'Nome',
    saveBlock: 'Salvar Quadra',
    cancel: 'Cancelar',
    deleteConfirm: 'Excluir esta quadra?',
    tapToStart: 'Toque no mapa para iniciar o limite',
    closeHint: 'Toque no primeiro vértice para fechar',
    unitCount: 'unidades',
    noBlocks: 'Nenhuma quadra desenhada',
    area: 'Área',
    emptyBoundary: 'Sem limite definido',
    newLot: 'Novo Lote',
    newBuilding: 'Nova Edific.',
    multiLayerHint: 'Desative camadas extras para editar',
    deleteQuadra: 'Excluir Quadra',
    deleteLot: 'Excluir Lote',
    deleteBuilding: 'Excluir Edific.',
    deleteLotsConfirm: 'Excluir lotes também?',
    deleteBuildingsConfirm: 'Excluir edificações também?',
    keep: 'Manter',
    loseEditingTitle: 'Perder edição?',
    loseEditingMsg: 'O polígono em andamento será perdido.',
    editBlock: 'Editar',
    deleteBlock: 'Excluir',
    autoSaved: 'Salvo',
    reference: 'Ref.',
    newBlock: 'Nova Quadra',
    blockInfo: 'Info da Quadra',
    confirmDeleteBlock: 'Excluir esta quadra e todos os lotes/edificações?',
    confirmDeleteLot: 'Excluir este lote?',
    confirmDeleteBuilding: 'Excluir esta edificação?',
  },
  settings: {
    title: 'Configurações',
    syncTitle: 'Sincronização',
    syncStatus: 'Status',
    syncPending: 'Pendente',
    syncOk: 'Atualizado',
    syncNow: 'Sincronizar agora',
    syncWifiOnly: 'Somente Wi-Fi',
    generalTitle: 'Geral',
    darkMode: 'Modo Escuro',
    keepScreenOn: 'Manter Tela Ligada',
    notifications: 'Notificações',
    aboutTitle: 'Sobre',
    helpSupport: 'Ajuda e Suporte',
    termsPrivacy: 'Termos e Privacidade',
    version: 'Versão',
    logout: 'Sair da conta',
    colorMode: 'Modo de Iluminação',
    colorModeSystem: 'Sistema',
    colorModeLight: 'Claro',
    colorModeDark: 'Escuro',
    autoCapture: 'Captura automática',
    autoCaptureDesc: 'Captura a foto automaticamente quando o documento estiver bem posicionado',
    autoSuggest: 'Sugestão automática',
    autoSuggestDesc: 'Sugere trocar modo conforme horário do dia',
    themeSuggestionTitle: 'Trocar modo de iluminação?',
    themeSuggestionDark: 'Já é noite. Deseja trocar para modo escuro?',
    themeSuggestionLight: 'Bom dia! Deseja trocar para modo claro?',
    themeSuggestionDismiss: 'Agora não',
    themeSuggestionAccept: 'Trocar',
    themeSuggestionDisable: 'Não sugerir novamente',
  },
  legal: {
    title: 'Termos e Privacidade',
    subtitle: 'Leia com atenção antes de prosseguir',
    termsTitle: 'Termos de Uso',
    privacyTitle: 'Política de Privacidade',
    checkboxTerms: 'Li e aceito os Termos de Uso',
    checkboxPrivacy: 'Li e aceito a Política de Privacidade',
    continueButton: 'Continuar',
    acceptedVersion: 'Versão aceita',
    acceptedAt: 'Aceito em',
    revokeTitle: 'Revogar Consentimento',
    revokeDescription: 'Ao revogar seu consentimento, você será desconectado e não poderá usar o aplicativo até aceitar novamente.',
    revokeButton: 'Revogar e Sair',
  },
  errors: {
    network: 'Sem conexão com a internet.',
    gps: 'GPS indisponível. Verifique as permissões.',
    storage: 'Espaço insuficiente no dispositivo.',
    cpfInvalid: 'CPF inválido. Verifique os dígitos.',
    required: 'Campo obrigatório.',
    generic: 'Ocorreu um erro inesperado.',
    unauthorized: 'Sem permissão para esta ação.',
  },
  holderForm: {
    documentTitle: 'Documento',
    personalTitle: 'Dados Pessoais',
    spouseTitle: 'Cônjuge',
    occupationTitle: 'Profissão',
    contactTitle: 'Contato',
    cpfLabel: 'CPF',
    cpfPlaceholder: '000.000.000-00',
    rgLabel: 'RG',
    rgPlaceholder: 'Número do RG',
    rgIssuerLabel: 'Órgão Emissor',
    rgIssuerPlaceholder: 'Ex: SSP/SP',
    nameLabel: 'Nome Completo',
    namePlaceholder: 'Nome completo do titular',
    socialNameLabel: 'Nome Social',
    socialNamePlaceholder: 'Nome social (opcional)',
    birthDateLabel: 'Data de Nascimento',
    birthDatePlaceholder: 'DD/MM/AAAA',
    genderLabel: 'Gênero',
    filiationLabel: 'Filiação',
    filiationPlaceholder: 'Nome do pai ou mãe',
    filiationAddButton: 'Adicionar filiação',
    maritalStatusLabel: 'Estado Civil',
    spouseNameLabel: 'Nome do Cônjuge',
    spouseNamePlaceholder: 'Nome completo do cônjuge',
    spouseCpfLabel: 'CPF do Cônjuge',
    spouseCpfPlaceholder: '000.000.000-00',
    stableUnionLabel: 'União Estável',
    occupationTypeLabel: 'Tipo de Ocupação',
    occupationDescLabel: 'Descrição da Ocupação',
    occupationDescPlaceholder: 'Descreva a ocupação',
    professionLabel: 'Profissão',
    professionPlaceholder: 'Ex: Pedreiro, Costureira',
    professionDescLabel: 'Descrição da Profissão',
    professionDescPlaceholder: 'Descreva a profissão',
    residenceTimeLabel: 'Tempo de Residência',
    residenceTimePlaceholder: 'Ex: 5 anos',
    emailLabel: 'E-mail',
    emailPlaceholder: 'email@exemplo.com',
    phoneLabel: 'Telefone',
    phonePlaceholder: '(00) 00000-0000',
    phoneSecondaryLabel: 'Telefone Secundário',
    phoneSecondaryPlaceholder: '(00) 00000-0000',
    scanDocument: 'Escanear Documento',
    fillManually: 'Preencher Manual',
    editDocument: 'Editar Documento',
    fillSection: 'Preencher',
    editSection: 'Editar',
    saveHolder: 'Salvar Titular',
    savingHolder: 'Salvando titular...',
    holderSaved: 'Titular salvo com sucesso!',
    holderSaveError: 'Erro ao salvar titular',
    noData: 'Nenhum dado preenchido',
  },
  unitForm: {
    basicTitle: 'Informações Básicas',
    addressTitle: 'Endereço',
    photosTitle: 'Fotos da Fachada',
    areaTitle: 'Área e Dimensões',
    comingSoon: 'Em breve',
    communityLabel: 'Comunidade',
    attendanceLabel: 'Status de Atendimento',
    occupantLabel: 'Tipo de Ocupante',
    usageLabel: 'Tipo de Uso',
    conditionLabel: 'Condição',
    saveStep: 'Salvar',
    confirmPhotos: 'Confirmar',
    takePhoto: 'Tirar Foto',
    pickGallery: 'Escolher da Galeria',
    photosCount: 'fotos capturadas',
    streetLabel: 'Logradouro',
    numberLabel: 'Número',
    complementLabel: 'Complemento',
    neighborhoodLabel: 'Bairro',
    cityLabel: 'Cidade',
    stateLabel: 'UF',
    zipLabel: 'CEP',
    editInfo: 'Editar Informações',
    editAddress: 'Editar Endereço',
    fillFromLocation: 'Preencher pela localização',
    viewPhotos: 'Ver Fotos',
    savingUnit: 'Salvando unidade...',
    unitSaved: 'Unidade criada com sucesso!',
    unitSaveError: 'Erro ao salvar unidade',
    signatureTitle: 'Assinatura',
    signatureCaptured: 'Assinatura capturada',
    signatureEmpty: 'Nenhuma assinatura coletada',
    signatureCapture: 'Capturar Assinatura',
    signatureEdit: 'Editar Assinatura',
    signatureConfirm: 'Confirmar Assinatura',
    signatureUndo: 'Corrigir',
    signatureClear: 'Limpar',
    signatureGuide: 'Assine acima da linha',
  },
  croqui: {
    title: 'Croqui do Lote',
    modeGeral: 'Geral',
    modeLot: 'Lote',
    modeBuilding: 'Edificações',
    modePin: 'Pin',
    undo: 'Desfazer',
    closePolygon: 'Fechar',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    deleteBuilding: 'Excluir Edificação',
    areaLabel: 'Área',
    buildingsLabel: 'Edificações',
    noBoundary: 'Nenhum croqui registrado',
    drawSketch: 'Desenhar Croqui',
    editSketch: 'Editar Croqui',
    lotArea: 'Lote',
    buildingCount: 'edificações',
    tapToAddVertex: 'Toque no mapa para adicionar vértices',
    tapFirstToClose: 'Toque no primeiro vértice para fechar',
    minVertices: 'Mínimo 3 vértices para fechar',
    selfIntersection: 'Polígono com auto-interseção',
    buildingOutsideLot: 'Edificação fora do lote',
    drawLotFirst: 'Desenhe o lote primeiro',
    buildingType: 'Tipo da Edificação',
    buildingLabel: 'Rótulo',
    buildingLabelPlaceholder: 'Ex: Casa principal',
    buildingFloors: 'Pavimentos',
    typeCasa: 'Casa',
    typeEdicula: 'Edícula',
    typeGaragem: 'Garagem',
    typeComercial: 'Comercial',
    typeOutro: 'Outro',
    summaryLot: 'Lote',
    summaryBuildings: 'Edificações',
    noBuildings: 'Nenhuma edificação',
    // Step instructions
    stepGeral: 'Visão geral do croqui',
    stepPinMode: 'Toque para posicionar a unidade',
    stepLotStart: 'Passo 1: Toque nos cantos do lote',
    stepContinue: 'Continue marcando os cantos',
    stepCloseGreen: 'Toque no ponto verde para fechar',
    stepSelfIntersect: 'Linhas não podem se cruzar',
    stepDragAdjust: 'Arraste os pontos para ajustar',
    stepLotReady: 'Lote pronto. Confirme ou ajuste',
    stepBuildingStart: 'Toque nos cantos da edificação',
    stepBuildingClose: 'Toque no primeiro ponto para fechar',
    stepBuildingDrag: 'Arraste para ajustar a edificação',
    // Bottom bar buttons
    btnMinPoints: 'Marque pelo menos 3 pontos',
    btnStartLot: 'Desenhar Lote',
    btnStartBuilding: 'Desenhar Edificação',
    btnCloseLot: 'Fechar Lote',
    btnSaveCroqui: 'Salvar Croqui',
    btnDrawBuilding: 'Desenhar Edificação',
    btnCloseBuilding: 'Fechar Edificação',
    btnConfirmBuilding: 'Confirmar Edificação',
    btnAddBuilding: 'Adicionar Edificação',
    btnConfigBuilding: 'Configurar Edificação',
    btnSkipBuildings: 'Pular edificações',
    // Vertex context menu
    vertexDelete: 'Apagar',
    vertexMove: 'Mover',
    stepMoveVertex: 'Toque onde quer mover o ponto',
    // Info pill
    pillPoints: 'pts',
    pillBuildings: 'edific.',
    // Remembramento / Desmembramento
    btnRemembrar: 'Remembrar',
    btnDesmembrar: 'Desmembrar',
    remembramentoTitle: 'Remembramento de Lotes',
    remembramentoWarning: 'A união de lotes é aproximada. Ajuste os vértices manualmente depois.',
    desmembramentoTitle: 'Desmembramento de Lote',
    desmembramentoWarning: 'O corte do lote é aproximado. Ajuste os vértices manualmente depois.',
    stepRemembrar: 'Marque os cantos do 2º lote',
    stepRemembrarClose: 'Feche o 2º lote tocando no 1º ponto',
    stepDesmembrar: 'Marque os pontos da linha de corte',
    stepDesmembrarPick: 'Toque na metade que deseja manter',
    btnConfirmMerge: 'Confirmar União',
    btnConfirmSplit: 'Confirmar Corte',
    btnCut: 'Cortar',
    mergeError: 'Não foi possível unir os lotes. Verifique se eles se cruzam.',
    splitError: 'Não foi possível cortar o lote. Verifique os pontos de corte.',
  },
  areaDimensoes: {
    title: 'Áreas e Dimensões',
    // Modos do SegmentedControl
    modeGeral: 'Geral',
    modeLot: 'Lote',
    modeBuilding: 'Edificação',
    modePin: 'Pin',
    // Instruções por modo
    modeGeralHint: 'Visualização geral do contexto',
    selectLot: 'Toque em um lote para selecionar',
    selectBuildings: 'Toque nas edificações para vincular',
    lotSelected: 'Lote selecionado',
    buildingSelected: 'Edificação selecionada',
    buildingsSelected: 'edificação(ões)',
    // Ações
    btnDesmembrar: 'Desmembrar',
    btnRemembrar: 'Remembrar',
    btnConfirm: 'Confirmar Seleção',
    btnCancel: 'Cancelar',
    // Desmembramento
    stepCutPoints: 'Marque 2 pontos de corte no lote',
    btnCut: 'Cortar',
    stepPickHalf: 'Toque na metade que deseja manter',
    btnConfirmSplit: 'Confirmar Divisão',
    // Remembramento
    stepSelectSecondLot: 'Toque no lote adjacente para unir',
    btnConfirmMerge: 'Confirmar União',
    // Info
    noLots: 'Nenhum lote encontrado na região',
    noLotSelected: 'Selecione um lote primeiro',
    noBuildingSelected: 'Selecione uma edificação',
    mergeError: 'Não foi possível unir os lotes. Verifique se são adjacentes.',
    splitError: 'Não foi possível dividir. Tente com pontos diferentes.',
    pillArea: 'm²',
    pillBuildings: 'edific.',
  },
  drawing: {
    modeTitle: 'Desenhe livremente no mapa',
    brushLabel: 'Pincel',
    colorLabel: 'Cor',
    opacityLabel: 'Opacidade',
    saveDrawing: 'Salvar Desenho',
    clearConfirm: 'Limpar todos os traços?',
    capturePhoto: 'Foto do croqui',
  },
  photo: {
    retakeButton: 'Tirar novamente',
    proofOfResidenceLabel: 'Comprovante de Residência',
    propertyFacadeLabel: 'Fachada do Imóvel',
    proofOfResidenceEmpty: 'Nenhum comprovante capturado',
    propertyFacadeEmpty: 'Nenhuma foto da fachada capturada',
    captureProofOfResidence: 'Fotografar Comprovante',
    capturePropertyFacade: 'Fotografar Fachada',
  },
  hardDelete: {
    title: 'Exclusão permanente',
    description: (entity: string) =>
      `Você está prestes a excluir "${entity}". Esta ação é irreversível. Para confirmar, digite deletar abaixo.`,
    inputLabel: 'Digite "deletar" para confirmar',
  },
  common: {
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    save: 'Salvar',
    delete: 'Excluir',
    edit: 'Editar',
    back: 'Voltar',
    next: 'Próximo',
    previous: 'Anterior',
    loading: 'Carregando...',
    retry: 'Tentar novamente',
    close: 'Fechar',
    yes: 'Sim',
    no: 'Não',
    ok: 'OK',
    step: 'Passo',
    of: 'de',
  },
} as const;
